services:
  - type: web
    name: laxmi-mobile-stock
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn HospitalManagement.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: HospitalManagement.settings
      - key: SECRET_KEY
        value: django-insecure-9etypjz6%hz29_w@2+o_+mwr8xndx!s$i4vh_gslaqc_zjv#7w
      - key: DEBUG
        value: true
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_EJYXZL2jse6N@ep-lively-cloud-a17i2cw3-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
      - key: ALLOWED_HOSTS
        value: 127.0.0.1,localhost,laxmi-mobile-stock.onrender.com
