services:  
"  - type: web"  
"    name: laxmi-mobile-stock"  
"    env: python"  
"    buildCommand: \"pip install -r requirements.txt\""  
"    startCommand: \"gunicorn HospitalManagement.wsgi:application --bind 0.0.0.0:$PORT\""  
"    envVars:"  
"      - key: DJANGO_SETTINGS_MODULE"  
"        value: HospitalManagement.settings" 
