# Generated by Django 5.2 on 2025-04-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField()),
                ('add', models.CharField()),
                ('sell', models.IntegerField()),
                ('rest', models.CharField()),
            ],
        ),
    ]
