# Generated by Django 5.2 on 2025-04-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='date1',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='sell',
            new_name='remaining',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='add',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='rest',
        ),
        migrations.AddField(
            model_name='stock',
            name='contact',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='sold_today',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
