# Generated by Django 5.2 on 2025-04-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_rename_date1_stock_date_rename_sell_stock_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='wehave',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='sold_today',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
