# Generated by Django 5.2.1 on 2025-05-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_stock_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
