# Generated by Django 5.2 on 2025-04-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_stock_wehave_alter_stock_sold_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='wehave',
            field=models.IntegerField(default=0),
        ),
    ]
