# Generated by Django 5.2.1 on 2025-05-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_stock_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='system',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('store', 'date')},
        ),
    ]
