# Generated by Django 5.2 on 2025-04-26 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_remove_store_owner_stock_store'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='sold_today',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='wehave',
            field=models.IntegerField(),
        ),
    ]
