# Generated by Django 5.2.1 on 2025-05-29 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='note',
        ),
    ]
