# Generated by Django 5.2 on 2025-04-26 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_store_owner_alter_stock_sold_today_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='date',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='store',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='wehave',
        ),
    ]
