# Generated by Django 5.2.1 on 2025-05-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_remove_stock_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
