# Generated by Django 5.2 on 2025-04-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_workerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='review',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
