# Generated by Django 5.2 on 2025-04-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_store_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='system',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
