# Generated by Django 5.2 on 2025-05-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_stock_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='review',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sold_today',
            field=models.IntegerField(default=0),
        ),
    ]
