# Generated by Django 5.2 on 2025-05-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_alter_stock_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='review',
            new_name='review1',
        ),
        migrations.AddField(
            model_name='stock',
            name='review2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
