# Generated by Django 5.2 on 2025-05-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_rename_review_stock_review1_stock_review2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
