# Generated by Django 5.2 on 2025-05-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_stock_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
