# Generated by Django 5.2 on 2025-05-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_alter_stock_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='username',
        ),
    ]
